version: '3'

tasks:
  servidor:
    desc: Ejecuta el servidor
    cmds:
      - go run src/main/Modelo/EjecutaServidor.go {{.CLI_ARGS}} || true
    silent: true

  clean:
    desc: Elimina archivos de respaldo temporales, basura o binarios de compilación
    cmds:
      - find . -type f \( -name "*~" -o -name "#*#" \) -delete
      - rm -rf src/main/bin src/main/obj Documentacion/auto Documentacion/*.aux Documentacion/*.log- 
    silent: true

  cliente:
      desc: Ejecuta el cliente
      cmds:
        - dotnet run --project src/main/ -- {{.CLI_ARGS}}
    
