version: '3'

tasks:
  test_servidor:
    desc: Ejecuta los test para Servidor
    cmds:
      - go run src/test/Servidor_test.go
      - rm -rf bin
      - rm -rf Servidor_test
    silent: true
    
  servidor:
    desc: Ejecuta el servidor
    cmds:
      - go run src/main/Modelo/Servidor.go
      - rm -rf bin
      - rm -rf EjecutaServidor
    silent: true 
